"""followers

Revision ID: 44708b992f39
Revises: 7c5813910c70
Create Date: 2018-05-15 17:21:11.145123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44708b992f39'
down_revision = '7c5813910c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
